print("    ..-^~~~^-..  ")
print("  .~           ~. ")
print(" (;:           :;) ")
print("  (:           :)  ")
print("    ':._   _.:'  ")
print("        | |    ")
print("      (=====)  ")
print("        | |   ")
print("        | |  ")
print("        | |  ")
print("     ((/   \)) ")
print("BOOOOOOOOOOOOOOOOOOOM")

print("    ..-^~~~^-..  ")
print("  .~           ~. ")
print(" (;:           :;) ")
print("  (:           :)  ")
print("    ':._   _.:'  ")
print("        | |    ")
print("      (=====)  ")
print("        | |   ")
print("        | |  ")
print("        | |  ")
print("     ((/   \)) ")
print("BOOOOOOOOOOOOOOOOOOOM")


print("    ..-^~~~^-..  ")
print("  .~           ~. ")
print(" (;:           :;) ")
print("  (:           :)  ")
print("    ':._   _.:'  ")
print("        | |    ")
print("      (=====)  ")
print("        | |   ")
print("        | |  ")
print("        | |  ")
print("     ((/   \)) ")
print("BOOOOOOOOOOOOOOOOOOOM")

print("    ..-^~~~^-..  ")
print("  .~           ~. ")
print(" (;:           :;) ")
print("  (:           :)  ")
print("    ':._   _.:'  ")
print("        | |    ")
print("      (=====)  ")
print("        | |   ")
print("        | |  ")
print("        | |  ")
print("     ((/   \)) ")
print("BOOOOOOOOOOOOOOOOOOOM")