def nakresli():
	print("    ..-^~~~^-..  ")
	print("  .~           ~. ")
	print(" (;:           :;) ")
	print("  (:           :)  ")
	print("    ':._   _.:'  ")
	print("        | |    ")
	print("      (=====)  ")
	print("        | |   ")
	print("        | |  ")
	print("        | |  ")
	print("     ((/   \)) ")
	print("BOOOOOOOOOOOOOOOOOOOM")

nakresli()
nakresli()
nakresli()
nakresli()